rootLogger=INFO, console, file
appender.console.type=Console
appender.console.layout.pattern=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
appender.file.type=File
appender.file.fileName=./logs/mingsha-jvm.log
appender.file.layout.pattern=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
